 #comments begin with #                                                                                

# for convenience, define variable $(OBJS) to list of object files                                    
OBJS= main.c tokenizer.c history.c

# make has a "default rule" specifying how to build a an "object" file (.o) from a C source file (.c) 
#            this rule includes $(CFLAGS) as one of cc's parameters                                   
CFLAGS=-g -O3 # -g for debug, -O3 for optimization                                                    

# first target is built by default.  Usually named "all"                                              
all: tokenizer-fsbarron

# asciidraw (target) depends on all object files (prerequisites)                                      
tokenizer-fsbarron: $(OBJS)
	cc -o tokenizer-fsbarron $(CFLAGS) $(OBJS)

# all object files built from c files that include draw.h                                             
$(OBJS): tokenizer.h history.h

# deletes files generated by compilation                                                              
clean:
	rm -f *.o tokenizer-fsbarron

run:tokenizer-fsbarron
	./tokenizer-fsbarron
